#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2014 OpenWrt.org

START=99
STOP=16
USE_PROCD=1

run_mgmtlanip()
{
	local enabled
	config_get_bool enabled $1 enabled

	if [ "$enabled" = "1" ]; then
		local second exec
		config_get second $1 second
		if [ "$second" = "0" ] ; then
			second="10"
		fi
		exec="/etc/mgmtlanip.sh"
		chmod a+x $exec
		procd_open_instance
		procd_set_param command $exec
		procd_append_param command $second
		procd_set_param respawn
		echo "mgmtlanip service has started."
		procd_close_instance
	fi
}


service_triggers()
{
	procd_add_reload_trigger "mgmtlanip"
}

start_service() 
{
	config_load mgmtlanip
	config_foreach run_mgmtlanip service
}

stop_service()
{
	ps | grep -i mgmtlanip | grep -v grep  | awk '{print $1}' | xargs kill -s 9 2>/dev/null
	echo "mgmtlanip service has stoped."
}

